# Generated by Django 3.2.6 on 2023-12-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='middle_name',
            new_name='last_name',
        ),
    ]
